package leetcode;

import java.util.HashMap;

public class FindDifference_389 {
	
//	Given two strings s and t which consist of only lowercase letters.
//
//	String t is generated by random shuffling string s and then add one more letter at a random position.
//
//	Find the letter that was added in t.
//
//	Example:
//
//	Input:
//	s = "abcd"
//	t = "abcde"
//
//	Output:
//	e
//
//	Explanation:
//	'e' is the letter that was added.
	
	 public static char findTheDifference(String s, String t) {
		 
		 //s: abcd
		 //t: aabcd
		 HashMap<Integer, Character> hm = new HashMap<Integer, Character>();
		 
//		 if(s.length() == t.length()) return '0';
//		 if(s.length()< t.length()) return '0';
		 
		 boolean isDuplicate = false;
		 
		 for(int i = 0; i<s.length(); i++) {
			 hm.put(i, s.charAt(i));
		 }
		 
		 int index = 0;
		 for(int i = 0; i<s.length(); i++) {
			 while(index < s.length()) {
				 if(hm.get(index) == (s.charAt(i))) {
					 hm.remove(index);
					 s = s.substring(i);
				 }
				 index++;
			 }
		 }
		 
		 for(int i = 0;i<t.length(); i++) {
//			 if(!hm.containsValue(t.charAt(i)) )
//				 return t.charAt(i);
//		 }
		 System.out.println(hm.get(i));
//			
//		 System.out.println(s + " s:");
		 }
		 		 
		 return '0';
	    }
	 
	 public static void main(String[] args) {
		 String s="abdd";
		 String t="abddc";
		 
		 
		 System.out.println(findTheDifference(s,t));
	 }
	 

	 
	 
//	 int index = s.length();
//	 
//	 for(int i = 0; i< t.length(); i++) {
//		 
//		 while(t.charAt(i) == s.length()) {
//			 
//			 
//			 
//			 index--;
//		 }
//		 
//		 index = s.length();
//	 }
	 
}
